# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E49cusJPrxPxStL9s3ISFQwCNg0iTOhx
"""



import ipywidgets as widgets
from IPython.display import display, HTML
import re # For regular expressions to check character types

def check_password_strength(password):
    score = 0
    feedback = []

    # Criteria checks
    if len(password) >= 8:
        score += 1
    else:
        feedback.append("Password should be at least 8 characters long.")

    if re.search(r"[A-Z]", password):
        score += 1
    else:
        feedback.append("Password should contain at least one uppercase letter.")

    if re.search(r"[a-z]", password):
        score += 1
    else:
        feedback.append("Password should contain at least one lowercase letter.")

    if re.search(r"\d", password):
        score += 1
    else:
        feedback.append("Password should contain at least one digit.")

    if re.search(r"[^a-zA-Z0-9]", password):
        score += 1
    else:
        feedback.append("Password should contain at least one special character (e.g., !@#$%^&*).")

    # Determine strength based on score
    if score == 5:
        strength = "Very Strong 💪"
        color = "green"
    elif score >= 3:
        strength = "Moderate 👍"
        color = "orange"
    else:
        strength = "Weak 👎"
        color = "red"

    return strength, feedback, color

# Create widgets
password_input = widgets.Text(
    value='',
    placeholder='Enter your password here',
    description='Password:',
    disabled=False,
    continuous_update=False, # Assess strength only on unfocus or Enter key
    layout=widgets.Layout(width='auto')
)

strength_output = widgets.Output()

def on_password_change(change):
    with strength_output:
        strength_output.clear_output()
        password = change.new
        if password:
            strength, feedback, color = check_password_strength(password)
            display(HTML(f"<p style='color:{color}; font-weight:bold;'>Strength: {strength}</p>"))
            if feedback:
                display(HTML("<p>Suggestions:</p>"))
                for item in feedback:
                    display(HTML(f"<li style='color:gray;'>{item}</li>"))
        else:
            display(HTML("<p style='color:blue;'>Enter a password to check its strength.</p>"))

password_input.observe(on_password_change, names='value')

# Display the widgets
display(HTML("<h2>Password Strength Checker</h2>"))
display(password_input)
display(strength_output)